### ISSUE TITLE
could not locate "helveticaBB"

### ISSUE THREAD

**Issue by vladyslav2** [mandolyte/mdtopdf#18]
**Problem**

While working with this library I found an interesting case. If you create this markdown

```
### **Email:** issuer\_email
```

and when you try to convert, you will get an error:
```
➜  go run convert.go -i bad-markdown.md -o result.pdf 
2023/01/20 16:37:07 pdf.OutputFileAndClose() error:Pdf.OutputFileAndClose() error on result.pdf:could not locate "helveticaBB" among embedded core font definition files
```

**Additional info**
My understanding, gotopdf missing some fonts for italic headers

**Comment by mandolyte** [comment]
@vladyslav2 Since the gotopdf project is closed, do you have any ideas about how to address this (short of forking it)?

**Comment by vladyslav2** [comment]
@mandolyte based on the error, it looks like gotopdf does have some default settings for various fonts (italic, bold, semi-bold and etc) and helveticaBB does not support all of those font variations. My best shot - check gotopdf settings and see if its configurable

**Comment by FrankStienhans2** [comment]
Debugged it. The request into the SetFont method is "Arial" with Style "bb". This is being converted to "Hevetica" with style "bb". This is not defined as can be seen here: https://github.com/go-pdf/fpdf/tree/main/font_embed
<img width="609" alt="Screenshot 2024-06-19 at 10 47 30 AM" src="https://github.com/mandolyte/mdtopdf/assets/5828075/a8fd59d3-0150-4bee-9bb9-7d7e07dd3ca7">

**Comment by FrankStienhans2** [comment]
Not a fix but a functioning workaround:
```golang
func (r *PdfRenderer) processText(node *ast.Text) {
	currentStyle := r.cs.peek().textStyle
	if currentStyle.Style == "bb" { 
		currentStyle.Style = "b"
	}
	r.setStyler(currentStyle)
```

**Comment by jessp01** [comment]
Hi @FrankStienhans2 ,

Thank you for your debugging info.

I'll take a look at it.
Please note that a while back, I migrated the project from `blackfriday` to `gomarkdown` which is actively maintained (see https://github.com/mandolyte/mdtopdf/pull/40) but the issue is present when using that as well. 

If you want a workaround pro tem, I'd suggest applying it in `mdtopdf.go:setStyler()` rather than in `nodeProcessing.go:processText()`:

```go
func (r *PdfRenderer) setStyler(s Styler) {
        if s.Style == "bb" {
            s.Style = "b"
        }
        r.Pdf.SetFont(s.Font, s.Style, s.Size)
        r.Pdf.SetTextColor(s.TextColor.Red, s.TextColor.Green, s.TextColor.Blue)
        r.Pdf.SetFillColor(s.FillColor.Red, s.FillColor.Green, s.FillColor.Blue)
}
```

**Comment by jessp01** [comment]
So, the problem is here: https://github.com/mandolyte/mdtopdf/blob/master/nodeProcessing.go#L299

This can be easily solved with something like:
```go
if entering {
                if ! strings.Contains(r.cs.peek().textStyle.Style, "b"){
                    r.cs.peek().textStyle.Style += "b"
                }
...
```
But, because the code (rightly) removes the "b" when `entering` is false, with this change, the sample MD input (`## **Email**: issuer\_email`) would result in `Email` being bold and the reminder of the header ("issuer_email") in "normal" style.
I can address this by checking whether the parent element is a header but I suppose the real question is why would one use `**` (strong markup) within a header to begin with, considering the fact that headers are typically rendered in bold anyway, as they are (by default) in `mdtopdf` (see https://github.com/mandolyte/mdtopdf/blob/master/mdtopdf.go#L154).  Could you please tell me what your expectation is for such an input?

Cheers,

**Comment by Xanvial** [comment]
Hello, I encountered similar error,
for me the expectation is, it should ignore the strong markup. So will print as a header only.

For now I need to manually remove the `**` markdown if it's exist inside a header
