### ISSUE TITLE
UTF8

### ISSUE THREAD

**Issue by malaschitz** [mandolyte/mdtopdf#5]
Is able create pdf with some special chars ? In gofpdf is possible to use https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.UnicodeTranslatorFromDescriptor

**Comment by mandolyte** [comment]
@malaschitz  can you provide me a markdown document where this is present and needed? thanks!

**Comment by mandolyte** [comment]
@malaschitz since this conversion depends on what the BlackFriday markdown parser provides, I'm not sure that use of the replacement function for UTF8 is possible. So I'll go ahead and close this. If you do find a markdown document that exhibits the problem, please re-open this issue and send it to me.
