### ISSUE TITLE
get the latest version

### ISSUE THREAD

**Issue by lsy88** [mandolyte/mdtopdf#55]
Hi author, I noticed that the latest version has reached v2.2.4, but when I go get it, I only get v1.5.3, is there any way to use the latest code

**Comment by jessp01** [comment]
Hello @lsy88 ,

Yes, that's due to how Golang manages versions (see https://github.com/mandolyte/mdtopdf/issues/45).
However, you have pre-built binaries under https://github.com/mandolyte/mdtopdf/releases for every release and of course, you can also download/clone the code from the 2.2.4 tag and build it yourself if you wish.
